# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='data',
            field=models.CharField(max_length=132, verbose_name=b'CPU\xe6\x95\xb0\xe6\x8d\xae'),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='time',
            field=models.DateTimeField(verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
