# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteCMD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdlist',
            name='cmd',
            field=models.CharField(max_length=128, verbose_name=b'\xe5\x91\xbd\xe4\xbb\xa4'),
        ),
        migrations.AlterField(
            model_name='cmdlist',
            name='time',
            field=models.DateTimeField(verbose_name=b'\xe5\x8f\x91\xe5\x87\xba\xe5\x91\xbd\xe4\xbb\xa4\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
