# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteCMD', '0002_auto_20170717_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdlist',
            name='host',
            field=models.CharField(default=b'192.168.59.129', max_length=64, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba'),
        ),
    ]
