# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u7ec4\u540d')),
                ('description', models.TextField(verbose_name='\u7ec4\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('os', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu', models.CharField(max_length=32, verbose_name='CPU\u578b\u53f7')),
                ('last_login_time', models.DateTimeField(verbose_name='\u6700\u8fd1\u767b\u5f55\u65f6\u95f4')),
                ('delete_flag', models.BooleanField(verbose_name='\u5220\u9664\u6807\u5fd7')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6743\u9650\u540d')),
                ('description', models.TextField(verbose_name='\u6743\u9650\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
            ],
        ),
    ]
