# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu',
            field=models.CharField(max_length=128, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='last_login_time',
            field=models.CharField(max_length=128, verbose_name='\u6700\u8fd1\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='os',
            field=models.CharField(max_length=128, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
    ]
